### ISSUE TITLE
Signing up doesn't allow gameplay immediately afterwards

### ISSUE THREAD

**Issue by chinawat** [cpe200-161/WerewolfServer#22]
After signing up, the game window shows up, but the player can't join a new game.  The player needs to reconnect to the server using "sign in" next time around before successfully joining a game.

**Comment by pruet** [comment]
Seem like it's a WerewolfClient's issue, I'll close it for now and please resubmit this issue to https://github.com/cpe200-161/WerewolfClient/issues/. But if you feel that it needs a help from server side, please reopen it.
